version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      lockfile:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/apps/api"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
