export const TIER_FEATURES = {
  STARTER: {
    maxStaff: 1,
    maxBookingsPerMonth: Infinity,
    smsAllocation: 100,
    embedModes: ['redirect'] as const,
    clientManagement: 'basic' as const,
    contracts: 'basic' as const,
    analytics: 'basic' as const,
    teamManagement: false,
    multiLocation: false,
    customTemplates: false,
  },
  TEAM: {
    maxStaff: 10,
    maxBookingsPerMonth: Infinity,
    smsAllocation: 500,
    embedModes: ['redirect', 'popup', 'inline'] as const,
    clientManagement: 'full' as const,
    contracts: 'full' as const,
    analytics: 'advanced' as const,
    teamManagement: true,
    multiLocation: true,
    customTemplates: true,
  },
  BUSINESS: {
    maxStaff: Infinity,
    maxBookingsPerMonth: Infinity,
    smsAllocation: 2000,
    embedModes: ['redirect', 'popup', 'inline'] as const,
    clientManagement: 'full' as const,
    contracts: 'full' as const,
    analytics: 'advanced' as const,
    teamManagement: true,
    multiLocation: true,
    customTemplates: true,
  },
} as const;

export type FeatureKey = keyof typeof TIER_FEATURES.STARTER;
