export const BOOKING_STEPS = {
  SERVICE_SELECTION: 'SERVICE_SELECTION',
  VENUE_SELECTION: 'VENUE_SELECTION',
  DATE_TIME_PICKER: 'DATE_TIME_PICKER',
  GUEST_COUNT: 'GUEST_COUNT',
  QUESTIONNAIRE: 'QUESTIONNAIRE',
  ADD_ONS: 'ADD_ONS',
  PRICING_SUMMARY: 'PRICING_SUMMARY',
  CONTRACT: 'CONTRACT',
  PAYMENT: 'PAYMENT',
  CONFIRMATION: 'CONFIRMATION',
} as const;

export type BookingStep = (typeof BOOKING_STEPS)[keyof typeof BOOKING_STEPS];
