#!/usr/bin/env bash
# =============================================================================
# SavSpot — Generate JWT keys and encryption key
# =============================================================================
# Generates:
#   - RS256 key pair (JWT_PRIVATE_KEY_BASE64, JWT_PUBLIC_KEY_BASE64)
#   - 32-byte hex encryption key (ENCRYPTION_KEY)
#
# Usage:
#   ./scripts/generate-keys.sh          # Print to stdout
#   ./scripts/generate-keys.sh >> .env  # Append to .env file
# =============================================================================

set -euo pipefail

# Check for openssl
if ! command -v openssl &>/dev/null; then
  echo "Error: openssl is required but not installed." >&2
  exit 1
fi

# Generate RSA key pair in temp files
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

openssl genrsa -out "$TMPDIR/private.pem" 2048 2>/dev/null
openssl rsa -in "$TMPDIR/private.pem" -pubout -out "$TMPDIR/public.pem" 2>/dev/null

# Base64-encode (single line, no wrapping)
PRIVATE_B64=$(base64 -w 0 < "$TMPDIR/private.pem" 2>/dev/null || base64 < "$TMPDIR/private.pem" | tr -d '\n')
PUBLIC_B64=$(base64 -w 0 < "$TMPDIR/public.pem" 2>/dev/null || base64 < "$TMPDIR/public.pem" | tr -d '\n')

# Generate 32-byte encryption key
ENCRYPTION_KEY=$(openssl rand -hex 32)

echo "# Generated by scripts/generate-keys.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "JWT_PRIVATE_KEY_BASE64=$PRIVATE_B64"
echo "JWT_PUBLIC_KEY_BASE64=$PUBLIC_B64"
echo "ENCRYPTION_KEY=$ENCRYPTION_KEY"
